routes/web.php
<?php

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| This file is where you may define all of the routes that are handled
| by your application. Just tell Laravel the URIs it should respond
| to using a Closure or controller method. Build something great!
|
*/

// Route::get('/', function () {
//     return redirect('eShop');
// });

Route::resource('/eShop', 'ToyController');

// Route::('/eShop', 'ToysController@login'); 
//     return redirect('eShop');

Route::get('/', function(){ return redirect()->route('eShop.index'); });
Route::get('/home', function(){ return redirect()->route('eShop.index'); });

Auth::routes();

// Route::get('/home', 'HomeController@index');

Route::get('/map', 'MapsController@index');
Route::get('/contact', 'ContactController@index');

Route::resource('/user', 'UserController');

Route::get('/uploadfile','UploadFileController@index');
Route::post('/uploadfile','UploadFileController@showUploadFile');

resources/views/layout/footer.blade.php
<footer>   
    <div class="container">
        <div class="row">
            <div class="col-md-12 col-xs-12">
                <div class="col-md-3 col-xs-12">
                    <div class="info-box-title"><h4>Information</h4></div>
                    <ul class="list-unstyled">
                        <li><a href="{{ route('eShop.index') }}">Home</a></li>
                        <li><a href="{{ URL::to('contact') }}">Contact Us</a></li>
                    </ul>
                </div>
                <div class="col-md-3 col-xs-12">
                    <div class="info-box-title"><h4>Categories</h4></div>
                    <ul class="list-unstyled">
                        <li><a href="">Cars</a></li>
                        <li><a href="">Motorcycles</a></li>
                    </ul>
                </div>
                <div class="col-md-3 col-xs-12">
                    <div class="info-box-title"><h4>Extras</h4></div>
                    <ul class="list-unstyled">
                        <li><a href="{{ url('login') }}">Login</a></li>
                    </ul>
                </div>
                <div class="col-md-3 col-xs-12">
                    <div class="box-heading info-box-title">
                        <h4>Follow Us</h4>
                        <div class="facebook icon">
                            <a href="https://facebook.com" target="blank" title="Facebook"><i class="fa fa-facebook fa-2x" aria-hidden="true"></i></a>
                        </div>
                        <div class="twitter icon">
                            <a href="https://twitter.com" target="blank" title="Twitter"><i class="fa fa-twitter fa-2x" aria-hidden="true"></i></a>
                        </div>
                        <div class="google-plus icon">
                            <a href="https://plus.google.com" target="blank" title="Google-plus"><i class="fa fa-google-plus fa-2x"></i></a>
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </div>
</footer>
<div class="copy-right"><p>Created by <a class="anchor-fix" href="#">MnD </a>2016 &copy</p></div>

<!-- 
    |||||||||||||||||||||||||||||||||||||||||||||||||||||||||||||||||||||||||||||||||||||||
    ||||  ||||||||||  ||||||||    ||||  |||||||||||  ||       |||||||||  ||||          ||||
    ||||  ||||||||||  ||||||  ||||  |||  |||||||||  |||  ||||||||||||||  ||||||||  ||||||||
    ||||  ||||||||||  |||||  ||||||  |||  |||||||  ||||  ||||||||||||||  ||||||||  ||||||||
    ||||  ||||||||||  |||||  ||||||  ||||  |||||  |||||     |||||||||||  ||||||||  ||||||||
    ||||  ||||||||||  |||||  ||||||  |||||  |||  ||||||  ||||||||||||||  ||||||||  ||||||||
    ||||  ||||||||||  ||||||  ||||  |||||||  |  |||||||  ||||||||||||||  ||||||||  ||||||||
    ||||  ||||||||||      ||||    ||||||||||   ||||||||       |||||||||  ||||||||  ||||||||
    ||||||||||||||||||||||||||||||||||||||||||||||||||||||||||||||||||||||||||||||||||||||| -->
    
    <script type="text/javascript" src="http://code.jquery.com/jquery-1.11.0.min.js"></script>
    <script type="text/javascript" src="http://code.jquery.com/jquery-migrate-1.2.1.min.js"></script>
    <script type="text/javascript" src="http://cdnjs.cloudflare.com/ajax/libs/fancybox/1.3.4/jquery.fancybox-1.3.4.pack.min.js"></script>
    <script type="text/javascript">
    $(function($){
        var addToAll = false;
        var gallery = false;
        var titlePosition = 'inside';
        $(addToAll ? 'img' : 'img.fancybox').each(function(){
            var $this = $(this);
            var title = $this.attr('title');
            var src = $this.attr('data-big') || $this.attr('src');
            var a = $('<a href="#" class="fancybox"></a>').attr('href', src).attr('title', title);
            $this.wrap(a);
        });
        if (gallery)
            $('a.fancybox').attr('rel', 'fancyboxgallery');
        $('a.fancybox').fancybox({
            titlePosition: titlePosition
        });
    });
    $.noConflict();
    </script>
    <script src="https://code.jquery.com/jquery-3.1.1.min.js"></script>
    {{-- <script src="js/main.js"></script> --}}
    <script src="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/js/bootstrap.min.js"></script>
    
    <script type="text/javascript" src="http://ajax.aspnetcdn.com/ajax/jquery.validate/1.15.0/jquery.validate.js"></script>

   
    

<script>

$( "#myform" ).validate({
  rules: {
    name: {
      text: true
    }
  }
});
</script>
</body>
</html>

resources/views/layout/header.blade.php
<!DOCTYPE html>
<html lang="en">
    <head>
        <meta charset="utf-8">
        <meta http-equiv="X-UA-Compatible" content="IE=edge">
        <meta name="viewport" content="width=device-width, initial-scale=1">

        <link href="css/bootstrap.min.css" rel="stylesheet">
        <link rel="stylesheet" type="text/css" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/css/bootstrap.min.css">
        <link rel="stylesheet" type="text/css" href="{{asset('css/app.css') }}">
        <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/4.6.3/css/font-awesome.min.css">

        <title>PypPyp</title>

        <!-- Fonts -->
        <link href="https://fonts.googleapis.com/css?family=Droid+Serif:400,400i,700,700i" rel="stylesheet">
        <link href="https://fonts.googleapis.com/css?family=Anton" rel="stylesheet">
        <link href="https://fonts.googleapis.com/css?family=Acme|Indie+Flower|Nunito" rel="stylesheet">


        <link rel="stylesheet" type="text/css" media="screen" href="http://cdnjs.cloudflare.com/ajax/libs/fancybox/1.3.4/jquery.fancybox-1.3.4.css" />
       
        
    </head>
    

<body>
    <header>
        <div class="top-line">
            <div class="container">
                <div class="row">
                    <div class="col-md-6 col-xs-12">
                        <nav>
                            <ul>
                                <li><a href="{{ route('eShop.index') }}">home</a></li>
                                {{-- <li><a href="{{ URL::to('map') }}">map</a></li> --}}
                                <li><a href="{{ URL::to('contact') }}">contact us</a></li>
                                 
                            @if(!Auth::guest() && Auth::user()->is_admin)
                                <li><a href="#"></a></li>
                                <li><a href="{{ route('user.index') }}">users</a></li>
                            @else
                            @endif

                            </ul>
                        </nav>
                    </div>
                    <div class="shopping-cart">
               
                    @if (Auth::guest())
                    
                        <li><a href="{{ url('/login') }}">login <i class="fa fa-sign-in" aria-hidden="true"></i></a></li>
                        <li><a href="{{ url('/register') }}">register <i class="fa fa-user" aria-hidden="true"></i></a></li>

                    @else
                        <li class="dropdown">
                            <a href="#" class="dropdown-toggle" data-toggle="dropdown" role="button" aria-expanded="false">
                        {{ Auth::user()->name }} {{ Auth::user()->surname }} <span class="caret"></span>
                            </a>
                            <ul class="dropdown-menu" role="menu">
                                <li>
                                    <a href="{{ url('/logout') }}"
                                    onclick="event.preventDefault();
                                    document.getElementById('logout-form').submit();">
                                    Logout
                                    </a>

                                    <form id="logout-form" action="{{ url('/logout') }}" method="POST" style="display: none;">
                                        {{ csrf_field() }}
                                    </form>
                                </li>
                            </ul>
                        </li>

                    @endif
                    
                    </div>    
                </div> <!-- row -->
            </div> <!-- container -->
        </div> <!-- top-line -->
        <div class="container header-text">
            <div class="row">
                <div class="col-xs-12">
                    <div class="header-title"><h2>Battery-powered Toys</h2></div>
                </div>
            </div>
            <!-- <div class="navigation">
                <nav>
                    <ul>
                        <li><a href="">jeep</a></li>
                        <li><a href="">motorcycle</a></li>
                        <li><a href="">bat-mobile</a></li> 
                      
                    </ul>
                </nav>
            </div> -->
        </div>
</header>