routes/web.php
<?php

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| This file is where you may define all of the routes that are handled
| by your application. Just tell Laravel the URIs it should respond
| to using a Closure or controller method. Build something great!
|
*/

// Route::get('/', function () {
//     return redirect('eShop');
// });

Route::resource('/eShop', 'ToyController');

// Route::('/eShop', 'ToysController@login'); 
//     return redirect('eShop');

Route::get('/', function(){ return redirect()->route('eShop.index'); });
Route::get('/home', function(){ return redirect()->route('eShop.index'); });

Auth::routes();

// Route::get('/home', 'HomeController@index');

Route::get('/map', 'MapsController@index');
Route::get('/contact', 'ContactController@index');

Route::resource('/user', 'UserController');

Route::get('/uploadfile','UploadFileController@index');
Route::post('/uploadfile','UploadFileController@showUploadFile');

app/User.php
<?php

namespace App;

use Illuminate\Notifications\Notifiable;
use Illuminate\Foundation\Auth\User as Authenticatable;

class User extends Authenticatable
{
    use Notifiable;

    /**
     * The attributes that are mass assignable.
     *
     * @var array
     */



    protected $fillable = [
        'name', 'surname', 'email', 'password', 'is_admin'
    ];

    /**
     * The attributes that should be hidden for arrays.
     *
     * @var array
     */
    protected $hidden = [
        'password', 'remember_token', 
    ];
}

app/Http/Controllers/UserController.php
<?php

namespace App\Http\Controllers;

use Illuminate\Http\Request;
use Auth;

class UserController extends Controller
{
    public function __construct() {
        $this->middleware(function($request, $next){
            if(\Auth::guest() || (!\Auth::guest() && \Auth::user()->is_admin == 0)){
                return redirect()->route('login');
           }
        return $next($request);
       });
    }
    
    /**
     * Display a listing of the resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function index()
    {
        $users = \App\User::all();
        // var_dump($users);
        // return view('user.index');
        return view('user.index', compact('users'));
    }

    /**
     * Show the form for creating a new resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function create()
    {
        return view('user.create');
    }

    /**
     * Store a newly created resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @return \Illuminate\Http\Response
     */
    public function store(Request $request)
    {
        $user = new \App\User();

        $user->name         = $request->name; 
        $user->surname      = $request->surname;
        $user->email        = $request->email;
         

        $user->save();

        return redirect()->route('user.index');
    }

    /**
     * Display the specified resource.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function show($id)
    {
        $user = \App\User::find($id);

        return view('user.show', compact('user'));
    }

    /**
     * Show the form for editing the specified resource.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function edit($id)
    {
        $user = \App\User::find($id);
        // var_dump($user);

        return view('user.create', compact('user'));
    }

    /**
     * Update the specified resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function update(Request $request, $id)
    {
        $data = $request->all();
        
        // if(!empty($request->password)){
            // jei password laukas nera tuscias - perrasom masyvo 'password' reiksme su jo pacio reiksme tik uzhashinta
            // $data['password'] = \Hash::make($request->password);
        // }else{
            // ismetam 'password' key is masyvo, nes kitaip uzsaugotu kaip tuscia password'a
            // unset($data['password']);
        // }
        
        // atnaujinam user duomenis su modifikuotais duomenimis
        $user = \App\User::find($id)->update($data);

        return redirect()->route('user.index');
    }

    /**
     * Remove the specified resource from storage.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function destroy($id)
    {
        \App\User::find($id)->delete();

        return redirect()->route('user.index');
    }
}

resources/views/user/create.blade.php
@extends("main")

@section("content")

<article>
    <div class="container form-apply">
        <div class="row">
            <div class="col-md-12 ">
            	@if(isset($user))
            		<form id="myform"  method="POST" action="{{ route('user.update', $user->id) }}"  class="form-horizontal">
            			<input type="hidden" name="_method" value="put">
            	@else
                	<form class="form-horizontal" action="{{ route('user.store') }}" method="POST">
            	@endif
                
                {{ csrf_field() }}
					<fieldset>
						<legend>{{ isset($user) ? 'Edit users' : 'Create new user' }}</legend>
							<div class="form-group">
								<label class="col-md-4 control-label" for="textinput">Name</label>  
								<div class="col-md-4">
									@if(isset($user))
										<input value="{{ $user['name'] }}" name="name" type="text" placeholder="" class="form-control input-md">
									@else
										<input name="name" type="text" placeholder="" class="form-control input-md">
									@endif		
								</div>
							</div>
							<div class="form-group">
								<label class="col-md-4 control-label" for="textinput">Surname</label>  
								<div class="col-md-4">
									@if(isset($user))
										<input value="{{ $user['surname'] }}" name="surname" type="text" placeholder="" class="form-control input-md">
									@else
										<input name="surname" type="text" placeholder="" class="form-control input-md">
									@endif		
								</div>
							</div>
							<div class="form-group">
								<label class="col-md-4 control-label" for="textinput">Email</label>  
								<div class="col-md-4">
									@if(isset($user))
										<input value="{{ $user['email'] }}" name="email" type="text" placeholder="" class="form-control input-md">
									@else
										<input name="email" type="text" placeholder="" class="form-control input-md">
									@endif	
								</div>
							</div>
							<div class="form-group">
								<label class="col-md-4 control-label" for="textinput"></label>  
								<div class="col-md-4">
									@if($user->is_admin == 1)
										<input type="hidden" name="is_admin" value="0">
  										<input type="checkbox" checked="" name="is_admin" value="1"> This user has Admin rights<br>
									@else
  										<input type="hidden" name="is_admin" value="0">
  										<input type="checkbox" name="is_admin" value="1"> Make this user Admin
									@endif	
								</div>
							</div>

							<div class="form-group">
								<label class="col-md-4 control-label" for="singlebutton"></label>
								<div class="col-md-4">
									<input type="submit" name="save" class="btn btn-inverse"></input>
								</div>
							</div>
					</fieldset>
				</form>
			</div>
        </div>
    </div> <!-- container main -->   
</article> 



@endsection

resources/views/user/index.blade.php
@include("layout.header")



	@yield("content")

	<div class="container form-apply">
        <div class="row">
            <div class="col-md-12 col-sm-12 col-xs-12 ">
            	<fieldset>
					<legend>Users list</legend>
					<table class="user-table" >
						<tbody>
							<tr>
								<th>Name</th>
								<th>Surname</th>
								<th>Email</th>
								<th>Edit user</th>
								<th>Delete user</th>
							</tr>
							@foreach ($users as $user)
							<tr>
								<td>{{ $user->name }}</td>
								<td>{{ $user->surname }}</td>
								<td>{{ $user->email }}</td>
								<td><a href="{{ route('user.edit', $user->id) }}" class="btn btn-success">Edit</td>
								<td>
							@if(isset($user))
									<form method="POST" action="{{ route('user.destroy', $user->id) }}">
        								<input type="hidden" name="_method" value="DELETE">
        								{{ csrf_field() }}
        								<button class="btn btn-danger">Delete</button>
									</form>
        					@endif	
								</td>
							</tr>
							@endforeach
						</tbody>	
					</table>
				</fieldset>
			</div>
        </div>
    </div> <!-- container main -->   
@include("layout.footer")
								
							