routes/web.php
<?php

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| This file is where you may define all of the routes that are handled
| by your application. Just tell Laravel the URIs it should respond
| to using a Closure or controller method. Build something great!
|
*/

// Route::get('/', function () {
//     return redirect('eShop');
// });

Route::resource('/eShop', 'ToyController');

// Route::('/eShop', 'ToysController@login'); 
//     return redirect('eShop');

Route::get('/', function(){ return redirect()->route('eShop.index'); });
Route::get('/home', function(){ return redirect()->route('eShop.index'); });

Auth::routes();

// Route::get('/home', 'HomeController@index');

Route::get('/map', 'MapsController@index');
Route::get('/contact', 'ContactController@index');

Route::resource('/user', 'UserController');

Route::get('/uploadfile','UploadFileController@index');
Route::post('/uploadfile','UploadFileController@showUploadFile');

resources/views/eShop/create.blade.php
@extends("main")

@section("content")

<article>
    <div class="container form-apply">
        <div class="row">
            <div class="col-md-12 ">
            	@if(isset($toy))
            		{{ Form::open(['method' => 'POST', 'class' => 'form-horizontal', 'route' => ['eShop.update', $toy->id]] ) }}
            		<form  method="POST" action="{{ route('eShop.update', $toy->id) }}" class="form-horizontal">
            			{{ Form::hidden('_method', 'put') }}	
            		@else
                	<form class="form-horizontal" action="{{ route('eShop.store') }}" method="POST">
            	@endif
                
                {{ csrf_field() }}
					<fieldset>
						<legend>{{ isset($toy) ? 'Edit product' : 'Add new product' }}</legend>
							<div class="form-group">
								{{ Form::label('Item title', '', ['class' => 'col-md-4 control-label']) }}
								<div class="col-md-4">
									@if(isset($toy))
										{{ Form::text('title', $toy['title'],
										['class' => 'form-control input-md']) }}
									@else
										{{ Form::text('title', '',
										['class' => 'form-control input-md']) }}
									@endif		
								</div>
							</div>
							<div class="form-group">
								{{ Form::label('Price', '', ['class' => 'col-md-4 control-label']) }}
								<div class="col-md-4">
									@if(isset($toy))
										{{ Form::number('price', $toy['price'], 
										['class' => 'form-control input md']) }}
									@else
										{{ Form::number('price', '', 
										['class' => 'form-control input-md']) }}	
									@endif	
								</div>
							</div>
							<div class="form-group">
								{{ Form::label('Description', '', ['class' => 'col-md-4 control-label']) }}
								<div class="col-md-4">
									@if(isset($toy))
										{{ Form::textarea('description', $toy['description'], 
										['rows' => 5, 'class' => 'form-control']) }}                     
									@else
										{{ Form::textarea('description', '', 
										['rows'=> 5, 'class' => 'form-control']) }}	
									@endif	
								</div>
							</div>
							<div class="form-group">
								{{ Form::label('Image URL', '', ['class' => 'col-md-4 control-label']) }}
								<div class="col-md-4">
									@if(isset($toy))
										{{ Form::textarea('image', $toy['image'], 
										['rows' => 5, 'class' => 'form-control']) }}	                     
									@else
										
									@endif	
								</div>
							</div>
							<div class="form-group">
								{{ Form::label('Select the file to upload', '', ['class' => 'col-md-4 control-label']) }}
								<div class="col-md-4">
							<?php
						         echo Form::open(array('url' => '/uploadfile','files'=>'true'));
						       
						         echo Form::file('image');
						         
						         echo Form::close();
						     ?>
								</div>
							</div>

		
							<div class="form-group">
								{{ Form::label('', '', ['class' => 'col-md-4 control-label']) }}
								<div class="col-md-4">
									{{Form::submit('save', ['class' => 'btn btn-inverse'] )}}
								</div>
							</div>
					</fieldset>
				</form>
				<div class="form-group">
					{{form::label('','',['class' => 'col-md-4 control-label'])}}
					<div class="col-md-4">
						@if(isset($toy))
							<form method="POST" action="{{ route('eShop.destroy', $toy->id) }}">
								{{Form::hidden('_method', 'delete')}}
            						{{ csrf_field() }}
            					{{Form::submit('Delete', ['class' => 'btn btn-danger pull-right'])}}
            				</form>
            			@endif
					</div>
				</div>
            </div>
        </div>
    </div> <!-- container main -->   
</article> 
									



@endsection

resources/views/eShop/index.blade.php
@extends("main")

@section("content")
<main>
	<div class="header-bg-image">
      <div class="navigation-text">
         <h1>ride on toys for boys and girls</h1>
            <a class="shop-now-btn" href="#items">View gallery</a>
      </div>
   </div>
	  <div class="container">
	     <div class="row news-bar">
	         <div class="col-md-6 col-xs-12 admin-buttons">
	            <ul>
                  @if(!Auth::guest() && Auth::user()->is_admin)
	                 <li><a href="{{ route('eShop.create') }}">add new item</a></li>
                    <li><a href="{{ URL('uploadfile') }}">upload toy image</a></li>
                  @else
                  @endif
	            </ul>
	         </div>
	      </div>
         <div id="items" class="row container-models">
            @foreach ($toys as $toy)
               <div class="col-md-3 col-sm-12 col-xs-12">
                  <div class="model">
                     <div class="model-description">
                    	   <a href=""><h4>{{ $toy->title }}</h4></a>
                     </div>
                     @if(!Auth::guest())
                        <div>
                           <a href="{{ route('eShop.show', $toy->id) }}"><img class="img-responsive toys-image" src="{{asset('uploads/'. $toy->image) }}" alt="jeep" ></a>
                        </div>
                        <div class="add-to-cart">
                           <a class="fancybox" href="{{'uploads/'. $toy->image }}"><i class="fa fa-search-plus"></i></a>
                        </div>
                     @else
                        <div>
                          <a href="{{ URL::to('login') }}"><img class="img-responsive toys-image" src="{{'uploads/'. $toy->image }}" alt="jeep" ></a>
                        </div>
                        <div class="add-to-cart">
                           <a class="fancybox" href="{{'uploads/'. $toy->image }}"><i class="fa fa-search-plus"></i></a>
                        </div>
                     @endif        
                     <div class="model-price">
                       	<p>{{ $toy->price }} €</p>
                     </div>
                           
                     @if(!Auth::guest() && Auth::user()->is_admin)
                       <button class="btn btn-warning"><a href="{{ route('eShop.edit', $toy->id) }}">Edit item</a></button>

                     @if(isset($toy))
                        <form method="POST" action="{{ route('eShop.destroy', $toy->id) }}">
                           <input type="hidden" name="_method" value="DELETE"><br>
                       {{ csrf_field() }}
                           <button class="btn btn-danger">Delete</button>
                        </form>
                     @else    
                     @endif
                     @endif
                  </div>
               </div>
            @endforeach
        </div> 
    </div> 
</main>
@endsection

resources/views/eShop/login.blade.php
@extends("main")

@section("content")

<article>
    <div class="container form-apply">
        <div class="row">
            <div class="col-md-6 log-in-form">
                <form>
               		<div class="existing-user">
                        <h3>Already have account</h3>
                    </div> 
                    <div class="form-group">
                        <label for="email">Email address:</label>
                        <input type="email" class="form-control" id="email">
                    </div>
                    <div class="form-group">
                        <label for="pwd">Password:</label>
                        <input type="password" class="form-control" id="pwd">
                    </div>
                    <div class="checkbox">
                        <label><input type="checkbox"> Remember me</label>
                        </div>
                    <button type="submit" class="btn btn-default">Submit</button>
                </form>
            </div>
            <div class="col-md-6 log-in-form">
                <form>
                    <div class="new-user">
                        <h3>Create new account</h3>
                    </div> 
                    <div class="form-group">
                        <label for="pwd">Name:</label>
                        <input type="text" class="form-control" id="name">
                    </div>
                    <div class="form-group">
                        <label for="email">Email address:</label>
                        <input type="email" class="form-control" id="email">
                    </div>
                    <div class="form-group">
                        <label for="pwd">Password:</label>
                        <input type="password" class="form-control" id="pwd">
                    </div>
                    <div class="checkbox">
                        <label><input type="checkbox"> Remember me</label>
                        </div>
                    <button type="submit" class="btn btn-default">Submit</button>
                </form>        
            </div>
        </div>
    </div> <!-- container main -->   
</article> 


@endsection

resources/views/eShop/show.blade.php
@extends("main")

@section("content")
<div class="container">
  <div id="items" class="row container-models">
      <div class="col-md-6 col-sm-12 col-xs-12">
         <div class="model">
            <div class="model-description">
              	<h3>{{ $toy->title }}</h3>
            </div>
            <div class="model-price">
              	<p>{{ $toy->price }} €</p>
            </div>
            <div>
            	<img class="img-responsive toys-image-description" src="{{asset('uploads/'. $toy->image) }}" alt="jeep" >
            </div>
         </div>
      </div>
      <div class="col-md-6 col-sm-12 col-xs-12">
          <div class="model">
            <div class="model-description">
              	
            </div>
            <div class="model-price">
              	
            </div>
            <div>
            	<h3>{{ $toy->description }}</h3>
            </div>
         </div>
      </div>
  </div> 
</div>           
                        

                        
                        
                        
     


@endsection